# Dockerfile
FROM node:18-alpine

WORKDIR /src

COPY . .

RUN npm install

ENV NEXT_PUBLIC_SITE_KEY=
ENV CAPTCHA_KEY=
ENV FILE_DESTINATION_PATH=
ENV MONGODB_URL=
ENV JWT_SECRET_KEY=
ENV MAILSERVER_BASEURL=
ENV MAILSERVER_API_KEY=
ENV NEXT_PUBLIC_API_DOMAIN=
ENV SOLUN_API_KEY=
ENV NEXT_PUBLIC_MAIN_DOMAIN=
ENV NEXT_PUBLIC_AUTH_DOMAIN=
ENV NEXT_PUBLIC_WEBMAIL_DOMAIN=
ENV NEXT_PUBLIC_WEBMAIL_AUTH_DOMAIN=
ENV NEXT_PUBLIC_MAIL_HOST=
ENV NEXT_PUBLIC_IMAP_PORT=
ENV NEXT_PUBLIC_SMTP_PORT=

CMD npm run live && npm run start